### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by 8ware**
* The resulting order of WireGuard's hooks should coincide with its lifecycle
* Using FQCNs is recommended by the official Ansible documentation

### CODE REVIEW

**Comment by 8ware** [comment]
FYI: This is a preliminary pull request. I implemented the actual solution for issue #135 in branch [8ware:consistent-hook-execution](/8ware/ansible-role-wireguard/commits/consistent-hook-execution).

**Review by githubixx — COMMENTED** [review]
Thanks for the PR! That's something I wanted to do anyways sooner or later :wink: I'm not 100% sure but I guess the FQDN commands were introduced together with Ansible collections in Ansible 2.9. But I was not able to verify that. But https://docs.ansible.com/ansible/latest/reference_appendices/faq.html mentions that Ansible 2.9 introduced collections and I think that was also the introduction of FQDN commands. That would also mean that https://github.com/githubixx/ansible-role-wireguard/blob/master/meta/main.yml#L8 needs to be changed end set to `2.9`. And this in turn means that the new version of this role would be `9.0.0` as this is a breaking change at least for some people. So this also something the `CHANGELOG` should mention.

I haven't tested the change yet but having a quick look it's LGTM.

**Comment by 8ware** [comment]
Thanks for your remarks. I updated the role metadata and adjusted the new release version to `9.0.0` as suggested.

**Review by githubixx — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
